[DRIVER_SETTINGS]
SEQ		U1.0
SLE     U1.0
USYS$SLE_PARAMS create db=on, identifiers=quoted

[PATHS]
; Path to the SQLite database for the Uniface Repository:
$DBMS        SLE:.\dbms\usys.db
; Path to the SQLite database for application data:
$DBMS_DEF    SLE:.\dbms\userdata.db

$SYS    $DBMS
$UUU    $DBMS
$IDF    $DBMS
$DEF    $DBMS_DEF

[ENTITIES]
COUNTRYFLAG.ACMECUST=$seq:.\dbms\countryflag.*
