[SERVERS]
learn    = "C:\Program Files (x86)\Uniface\10.3\common\bin\userver.exe" /dir="D:\Development\Uniface\10\learn\" /adm="C:\Program Files (x86)\Uniface\10.3\uniface\adm\" /asn=.\asn\wasv.asn
learn_debug = "C:\Program Files (x86)\Uniface\10.3\common\bin\userver.exe" /dir="D:\Development\Uniface\10\learn\" /adm="C:\Program Files (x86)\Uniface\10.3\uniface\adm\" /asn=.\asn\wasv.asn /max=1 /deb=localhost+13002:wait
