[SERVERS]
myapp    = "C:\Program Files (x86)\Uniface\10.3\common\bin\userver.exe" /dir="\\vmware-host\Shared Folders\Development\Uniface\10\myapp\" /adm="C:\Program Files (x86)\Uniface\10.3\uniface\adm\" /asn=.\asn\wasv.asn
myapp_debug = "C:\Program Files (x86)\Uniface\10.3\common\bin\userver.exe" /dir="\\vmware-host\Shared Folders\Development\Uniface\10\myapp\" /adm="C:\Program Files (x86)\Uniface\10.3\uniface\adm\" /asn=.\asn\wasv.asn /max=1 /deb=localhost+13002:wait
