#file .\asn\ide.asn

[LOGICALS]
IDETITLE=Uniface eLearning (VC)

; Custom worksheets
;IDE_DEFINE_WORKSHEETS_CPT=HTML_PREVIEW
;IDE_DEFINE_WORKSHEETS_PRJ=MAINT_PROJECT
IDE_DEFINE_USERMENUS = VC_UPDATED
